# ArgoCD App: Namespaces with Istio Ambient labels
# @author Shanaka Jayasundera - shanakaj@gmail.com
#
# LAYER 3: EKS Customizations (ArgoCD)
# Sync Wave: 1 (creates namespaces for other apps)
#
# Namespaces are labelled with istio.io/dataplane-mode: ambient
# to enable automatic L4 mTLS via ztunnel (no sidecar injection needed)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/shanaka-versent/munchgo-aws-iac.git
    targetRevision: HEAD
    path: k8s
    directory:
      include: "namespace.yaml"

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
