# ArgoCD App: Istiod (Istio Control Plane - Ambient Mode)
# @author Shanaka Jayasundera - shanakaj@gmail.com
#
# LAYER 3: EKS Customizations (ArgoCD)
# Sync Wave: 0 (after CRDs)
#
# Istiod is the Istio control plane. With profile: ambient, it manages
# the ztunnel DaemonSet for automatic L4 mTLS between all mesh pods.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.24.0
    helm:
      releaseName: istiod
      values: |
        profile: ambient
        meshConfig:
          accessLogFile: /dev/stdout
        # Run istiod on system nodes
        pilot:
          nodeSelector:
            node-role: system
          tolerations:
            - key: CriticalAddonsOnly
              operator: Exists
              effect: NoSchedule

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
