# ArgoCD App: Istio CNI (for Ambient Mesh)
# @author Shanaka Jayasundera - shanakaj@gmail.com
#
# LAYER 3: EKS Customizations (ArgoCD)
# Sync Wave: 0 (with istiod)
#
# The CNI plugin configures network rules to redirect pod traffic
# through ztunnel for automatic mTLS. Required for Ambient mode.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: cni
    targetRevision: 1.24.0
    helm:
      releaseName: istio-cni
      values: |
        profile: ambient
        # CNI runs on all nodes (DaemonSet) - needs toleration for system nodes
        cni:
          tolerations:
            - key: CriticalAddonsOnly
              operator: Exists
              effect: NoSchedule

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
