# ArgoCD App: External Secrets Operator
# @author Shanaka Jayasundera - shanakaj@gmail.com
#
# LAYER 3: EKS Customizations (ArgoCD)
# Sync Wave: 8 (parallel with munchgo-apps, before apps need secrets)
#
# Deploys the External Secrets Operator via Helm chart.
# The operator syncs secrets from AWS Secrets Manager into K8s Secrets.
# MunchGo services use ExternalSecret resources to pull:
#   - RDS PostgreSQL credentials (per-service database)
#   - MSK Kafka bootstrap server endpoints
#
# Authentication: IRSA (service account → IAM role via OIDC federation)
# The IAM role is created by Terraform (iam module, enable_external_secrets=true)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.10.7
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true
        webhook:
          port: 9443
        serviceAccount:
          name: external-secrets
          annotations:
            # IRSA annotation — updated after terraform apply with actual role ARN
            eks.amazonaws.com/role-arn: arn:aws:iam::675177357191:role/role-external-secrets-kong-gw-poc
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
            effect: NoSchedule

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
